server:
  port: 9090
spring:
  application:
    name: xiaoxiao-blogs-application
#配置数据源
  datasource:
    sql-script-encoding: utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xiaoxiao_borker?characterEncoding=UTF-8
    password: 159302
    username: root
    driver-class-name: com.mysql.jdbc.Driver

